### ISSUE TITLE
MOQT object payload carries a single track?

### ISSUE THREAD

**Issue by acbegen** [wilaw/moq-cmaf-packaging#1]
This is generally true for CMAF tracks, but there is an exception. For example, CMAF allows the combination of a video track along with subtitle tracks. That is, a CMAF track could carry video plus subtitle tracks together.

**Comment by wilaw** [comment]
Are you sure? What would the header for that track declare? CMAF spec section 7.3.2.1 "CMAF header" states that `"The MovieBox shall contain exactly one track containing media data as specified in subclause 7.3.2.2."`

**Comment by acbegen** [comment]
Checking it again, looks like I misremembered. CTA captions can be embedded in the video track (as SEI messages with the ccea brand). Beyond that, CMAF indeed requires single media tracks (DASH/HLS can still allow for multiplexed tracks if they would like to).
